/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValueSummaryRouteImport } from './routes/value-summary'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SupplierTermsRouteImport } from './routes/supplier-terms'
import { Route as SubscriberAgreementRouteImport } from './routes/subscriber-agreement'
import { Route as SubmitAogRouteImport } from './routes/submit-aog'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrePositioningRouteImport } from './routes/pre-positioning'
import { Route as PartsIntelligenceRouteImport } from './routes/parts-intelligence'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FleetNetworkRouteImport } from './routes/fleet-network'
import { Route as EnrolRouteImport } from './routes/enrol'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrandGuidelinesRouteImport } from './routes/brand-guidelines'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AogRiskIndexRouteImport } from './routes/aog-risk-index'
import { Route as AogCasesRouteImport } from './routes/aog-cases'
import { Route as AircraftRouteImport } from './routes/aircraft'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupplierIndexRouteImport } from './routes/supplier/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SuppliersApplyRouteImport } from './routes/suppliers/apply'
import { Route as SupplierQuoteHistoryRouteImport } from './routes/supplier/quote-history'
import { Route as SupplierProfileRouteImport } from './routes/supplier/profile'
import { Route as SupplierLoginRouteImport } from './routes/supplier/login'
import { Route as AogIdRouteImport } from './routes/aog.$id'
import { Route as AdminSuppliersRouteImport } from './routes/admin/suppliers'
import { Route as AdminRevenueRouteImport } from './routes/admin/revenue'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminEnrolmentsRouteImport } from './routes/admin/enrolments'
import { Route as AdminDataRouteImport } from './routes/admin/data'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminCommsRouteImport } from './routes/admin/comms'
import { Route as AdminAogRouteImport } from './routes/admin/aog'
import { Route as AdminAmoRouteImport } from './routes/admin/amo'
import { Route as AdminAircraftRouteImport } from './routes/admin/aircraft'
import { Route as ApiV1SplatRouteImport } from './routes/api/v1/$'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'
import { Route as ApiFilesIdRouteImport } from './routes/api/files/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ValueSummaryRoute = ValueSummaryRouteImport.update({
  id: '/value-summary',
  path: '/value-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierTermsRoute = SupplierTermsRouteImport.update({
  id: '/supplier-terms',
  path: '/supplier-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriberAgreementRoute = SubscriberAgreementRouteImport.update({
  id: '/subscriber-agreement',
  path: '/subscriber-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitAogRoute = SubmitAogRouteImport.update({
  id: '/submit-aog',
  path: '/submit-aog',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrePositioningRoute = PrePositioningRouteImport.update({
  id: '/pre-positioning',
  path: '/pre-positioning',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsIntelligenceRoute = PartsIntelligenceRouteImport.update({
  id: '/parts-intelligence',
  path: '/parts-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FleetNetworkRoute = FleetNetworkRouteImport.update({
  id: '/fleet-network',
  path: '/fleet-network',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrolRoute = EnrolRouteImport.update({
  id: '/enrol',
  path: '/enrol',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandGuidelinesRoute = BrandGuidelinesRouteImport.update({
  id: '/brand-guidelines',
  path: '/brand-guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AogRiskIndexRoute = AogRiskIndexRouteImport.update({
  id: '/aog-risk-index',
  path: '/aog-risk-index',
  getParentRoute: () => rootRouteImport,
} as any)
const AogCasesRoute = AogCasesRouteImport.update({
  id: '/aog-cases',
  path: '/aog-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AircraftRoute = AircraftRouteImport.update({
  id: '/aircraft',
  path: '/aircraft',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierIndexRoute = SupplierIndexRouteImport.update({
  id: '/supplier/',
  path: '/supplier/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersApplyRoute = SuppliersApplyRouteImport.update({
  id: '/suppliers/apply',
  path: '/suppliers/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierQuoteHistoryRoute = SupplierQuoteHistoryRouteImport.update({
  id: '/supplier/quote-history',
  path: '/supplier/quote-history',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierProfileRoute = SupplierProfileRouteImport.update({
  id: '/supplier/profile',
  path: '/supplier/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierLoginRoute = SupplierLoginRouteImport.update({
  id: '/supplier/login',
  path: '/supplier/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AogIdRoute = AogIdRouteImport.update({
  id: '/aog/$id',
  path: '/aog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSuppliersRoute = AdminSuppliersRouteImport.update({
  id: '/admin/suppliers',
  path: '/admin/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRevenueRoute = AdminRevenueRouteImport.update({
  id: '/admin/revenue',
  path: '/admin/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnrolmentsRoute = AdminEnrolmentsRouteImport.update({
  id: '/admin/enrolments',
  path: '/admin/enrolments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/admin/data',
  path: '/admin/data',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommsRoute = AdminCommsRouteImport.update({
  id: '/admin/comms',
  path: '/admin/comms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAogRoute = AdminAogRouteImport.update({
  id: '/admin/aog',
  path: '/admin/aog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAmoRoute = AdminAmoRouteImport.update({
  id: '/admin/amo',
  path: '/admin/amo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAircraftRoute = AdminAircraftRouteImport.update({
  id: '/admin/aircraft',
  path: '/admin/aircraft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SplatRoute = ApiV1SplatRouteImport.update({
  id: '/api/v1/$',
  path: '/api/v1/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesIdRoute = ApiFilesIdRouteImport.update({
  id: '/api/files/$id',
  path: '/api/files/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/aircraft': typeof AircraftRoute
  '/aog-cases': typeof AogCasesRoute
  '/aog-risk-index': typeof AogRiskIndexRoute
  '/billing': typeof BillingRoute
  '/brand-guidelines': typeof BrandGuidelinesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/enrol': typeof EnrolRoute
  '/fleet-network': typeof FleetNetworkRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/parts-intelligence': typeof PartsIntelligenceRoute
  '/pre-positioning': typeof PrePositioningRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/set-password': typeof SetPasswordRoute
  '/signup': typeof SignupRoute
  '/submit-aog': typeof SubmitAogRoute
  '/subscriber-agreement': typeof SubscriberAgreementRoute
  '/supplier-terms': typeof SupplierTermsRoute
  '/team': typeof TeamRoute
  '/value-summary': typeof ValueSummaryRoute
  '/admin/aircraft': typeof AdminAircraftRoute
  '/admin/amo': typeof AdminAmoRoute
  '/admin/aog': typeof AdminAogRoute
  '/admin/comms': typeof AdminCommsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/enrolments': typeof AdminEnrolmentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/aog/$id': typeof AogIdRoute
  '/supplier/login': typeof SupplierLoginRoute
  '/supplier/profile': typeof SupplierProfileRoute
  '/supplier/quote-history': typeof SupplierQuoteHistoryRoute
  '/suppliers/apply': typeof SuppliersApplyRoute
  '/admin/': typeof AdminIndexRoute
  '/supplier/': typeof SupplierIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/aircraft': typeof AircraftRoute
  '/aog-cases': typeof AogCasesRoute
  '/aog-risk-index': typeof AogRiskIndexRoute
  '/billing': typeof BillingRoute
  '/brand-guidelines': typeof BrandGuidelinesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/enrol': typeof EnrolRoute
  '/fleet-network': typeof FleetNetworkRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/parts-intelligence': typeof PartsIntelligenceRoute
  '/pre-positioning': typeof PrePositioningRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/set-password': typeof SetPasswordRoute
  '/signup': typeof SignupRoute
  '/submit-aog': typeof SubmitAogRoute
  '/subscriber-agreement': typeof SubscriberAgreementRoute
  '/supplier-terms': typeof SupplierTermsRoute
  '/team': typeof TeamRoute
  '/value-summary': typeof ValueSummaryRoute
  '/admin/aircraft': typeof AdminAircraftRoute
  '/admin/amo': typeof AdminAmoRoute
  '/admin/aog': typeof AdminAogRoute
  '/admin/comms': typeof AdminCommsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/enrolments': typeof AdminEnrolmentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/aog/$id': typeof AogIdRoute
  '/supplier/login': typeof SupplierLoginRoute
  '/supplier/profile': typeof SupplierProfileRoute
  '/supplier/quote-history': typeof SupplierQuoteHistoryRoute
  '/suppliers/apply': typeof SuppliersApplyRoute
  '/admin': typeof AdminIndexRoute
  '/supplier': typeof SupplierIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/aircraft': typeof AircraftRoute
  '/aog-cases': typeof AogCasesRoute
  '/aog-risk-index': typeof AogRiskIndexRoute
  '/billing': typeof BillingRoute
  '/brand-guidelines': typeof BrandGuidelinesRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/enrol': typeof EnrolRoute
  '/fleet-network': typeof FleetNetworkRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/notifications': typeof NotificationsRoute
  '/parts-intelligence': typeof PartsIntelligenceRoute
  '/pre-positioning': typeof PrePositioningRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRoute
  '/set-password': typeof SetPasswordRoute
  '/signup': typeof SignupRoute
  '/submit-aog': typeof SubmitAogRoute
  '/subscriber-agreement': typeof SubscriberAgreementRoute
  '/supplier-terms': typeof SupplierTermsRoute
  '/team': typeof TeamRoute
  '/value-summary': typeof ValueSummaryRoute
  '/admin/aircraft': typeof AdminAircraftRoute
  '/admin/amo': typeof AdminAmoRoute
  '/admin/aog': typeof AdminAogRoute
  '/admin/comms': typeof AdminCommsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/enrolments': typeof AdminEnrolmentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/revenue': typeof AdminRevenueRoute
  '/admin/suppliers': typeof AdminSuppliersRoute
  '/aog/$id': typeof AogIdRoute
  '/supplier/login': typeof SupplierLoginRoute
  '/supplier/profile': typeof SupplierProfileRoute
  '/supplier/quote-history': typeof SupplierQuoteHistoryRoute
  '/suppliers/apply': typeof SuppliersApplyRoute
  '/admin/': typeof AdminIndexRoute
  '/supplier/': typeof SupplierIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/files/$id': typeof ApiFilesIdRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
  '/api/v1/$': typeof ApiV1SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/aircraft'
    | '/aog-cases'
    | '/aog-risk-index'
    | '/billing'
    | '/brand-guidelines'
    | '/contact'
    | '/dashboard'
    | '/enrol'
    | '/fleet-network'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/parts-intelligence'
    | '/pre-positioning'
    | '/pricing'
    | '/privacy'
    | '/services'
    | '/set-password'
    | '/signup'
    | '/submit-aog'
    | '/subscriber-agreement'
    | '/supplier-terms'
    | '/team'
    | '/value-summary'
    | '/admin/aircraft'
    | '/admin/amo'
    | '/admin/aog'
    | '/admin/comms'
    | '/admin/customers'
    | '/admin/data'
    | '/admin/enrolments'
    | '/admin/login'
    | '/admin/revenue'
    | '/admin/suppliers'
    | '/aog/$id'
    | '/supplier/login'
    | '/supplier/profile'
    | '/supplier/quote-history'
    | '/suppliers/apply'
    | '/admin/'
    | '/supplier/'
    | '/api/auth/$'
    | '/api/files/$id'
    | '/api/stripe/webhook'
    | '/api/v1/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/aircraft'
    | '/aog-cases'
    | '/aog-risk-index'
    | '/billing'
    | '/brand-guidelines'
    | '/contact'
    | '/dashboard'
    | '/enrol'
    | '/fleet-network'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/parts-intelligence'
    | '/pre-positioning'
    | '/pricing'
    | '/privacy'
    | '/services'
    | '/set-password'
    | '/signup'
    | '/submit-aog'
    | '/subscriber-agreement'
    | '/supplier-terms'
    | '/team'
    | '/value-summary'
    | '/admin/aircraft'
    | '/admin/amo'
    | '/admin/aog'
    | '/admin/comms'
    | '/admin/customers'
    | '/admin/data'
    | '/admin/enrolments'
    | '/admin/login'
    | '/admin/revenue'
    | '/admin/suppliers'
    | '/aog/$id'
    | '/supplier/login'
    | '/supplier/profile'
    | '/supplier/quote-history'
    | '/suppliers/apply'
    | '/admin'
    | '/supplier'
    | '/api/auth/$'
    | '/api/files/$id'
    | '/api/stripe/webhook'
    | '/api/v1/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/aircraft'
    | '/aog-cases'
    | '/aog-risk-index'
    | '/billing'
    | '/brand-guidelines'
    | '/contact'
    | '/dashboard'
    | '/enrol'
    | '/fleet-network'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/messages'
    | '/notifications'
    | '/parts-intelligence'
    | '/pre-positioning'
    | '/pricing'
    | '/privacy'
    | '/services'
    | '/set-password'
    | '/signup'
    | '/submit-aog'
    | '/subscriber-agreement'
    | '/supplier-terms'
    | '/team'
    | '/value-summary'
    | '/admin/aircraft'
    | '/admin/amo'
    | '/admin/aog'
    | '/admin/comms'
    | '/admin/customers'
    | '/admin/data'
    | '/admin/enrolments'
    | '/admin/login'
    | '/admin/revenue'
    | '/admin/suppliers'
    | '/aog/$id'
    | '/supplier/login'
    | '/supplier/profile'
    | '/supplier/quote-history'
    | '/suppliers/apply'
    | '/admin/'
    | '/supplier/'
    | '/api/auth/$'
    | '/api/files/$id'
    | '/api/stripe/webhook'
    | '/api/v1/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AircraftRoute: typeof AircraftRoute
  AogCasesRoute: typeof AogCasesRoute
  AogRiskIndexRoute: typeof AogRiskIndexRoute
  BillingRoute: typeof BillingRoute
  BrandGuidelinesRoute: typeof BrandGuidelinesRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  EnrolRoute: typeof EnrolRoute
  FleetNetworkRoute: typeof FleetNetworkRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  PartsIntelligenceRoute: typeof PartsIntelligenceRoute
  PrePositioningRoute: typeof PrePositioningRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SignupRoute: typeof SignupRoute
  SubmitAogRoute: typeof SubmitAogRoute
  SubscriberAgreementRoute: typeof SubscriberAgreementRoute
  SupplierTermsRoute: typeof SupplierTermsRoute
  TeamRoute: typeof TeamRoute
  ValueSummaryRoute: typeof ValueSummaryRoute
  AdminAircraftRoute: typeof AdminAircraftRoute
  AdminAmoRoute: typeof AdminAmoRoute
  AdminAogRoute: typeof AdminAogRoute
  AdminCommsRoute: typeof AdminCommsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDataRoute: typeof AdminDataRoute
  AdminEnrolmentsRoute: typeof AdminEnrolmentsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminRevenueRoute: typeof AdminRevenueRoute
  AdminSuppliersRoute: typeof AdminSuppliersRoute
  AogIdRoute: typeof AogIdRoute
  SupplierLoginRoute: typeof SupplierLoginRoute
  SupplierProfileRoute: typeof SupplierProfileRoute
  SupplierQuoteHistoryRoute: typeof SupplierQuoteHistoryRoute
  SuppliersApplyRoute: typeof SuppliersApplyRoute
  AdminIndexRoute: typeof AdminIndexRoute
  SupplierIndexRoute: typeof SupplierIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiFilesIdRoute: typeof ApiFilesIdRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  ApiV1SplatRoute: typeof ApiV1SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/value-summary': {
      id: '/value-summary'
      path: '/value-summary'
      fullPath: '/value-summary'
      preLoaderRoute: typeof ValueSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier-terms': {
      id: '/supplier-terms'
      path: '/supplier-terms'
      fullPath: '/supplier-terms'
      preLoaderRoute: typeof SupplierTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriber-agreement': {
      id: '/subscriber-agreement'
      path: '/subscriber-agreement'
      fullPath: '/subscriber-agreement'
      preLoaderRoute: typeof SubscriberAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit-aog': {
      id: '/submit-aog'
      path: '/submit-aog'
      fullPath: '/submit-aog'
      preLoaderRoute: typeof SubmitAogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pre-positioning': {
      id: '/pre-positioning'
      path: '/pre-positioning'
      fullPath: '/pre-positioning'
      preLoaderRoute: typeof PrePositioningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts-intelligence': {
      id: '/parts-intelligence'
      path: '/parts-intelligence'
      fullPath: '/parts-intelligence'
      preLoaderRoute: typeof PartsIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fleet-network': {
      id: '/fleet-network'
      path: '/fleet-network'
      fullPath: '/fleet-network'
      preLoaderRoute: typeof FleetNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrol': {
      id: '/enrol'
      path: '/enrol'
      fullPath: '/enrol'
      preLoaderRoute: typeof EnrolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-guidelines': {
      id: '/brand-guidelines'
      path: '/brand-guidelines'
      fullPath: '/brand-guidelines'
      preLoaderRoute: typeof BrandGuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aog-risk-index': {
      id: '/aog-risk-index'
      path: '/aog-risk-index'
      fullPath: '/aog-risk-index'
      preLoaderRoute: typeof AogRiskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aog-cases': {
      id: '/aog-cases'
      path: '/aog-cases'
      fullPath: '/aog-cases'
      preLoaderRoute: typeof AogCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aircraft': {
      id: '/aircraft'
      path: '/aircraft'
      fullPath: '/aircraft'
      preLoaderRoute: typeof AircraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/': {
      id: '/supplier/'
      path: '/supplier'
      fullPath: '/supplier/'
      preLoaderRoute: typeof SupplierIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/apply': {
      id: '/suppliers/apply'
      path: '/suppliers/apply'
      fullPath: '/suppliers/apply'
      preLoaderRoute: typeof SuppliersApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/quote-history': {
      id: '/supplier/quote-history'
      path: '/supplier/quote-history'
      fullPath: '/supplier/quote-history'
      preLoaderRoute: typeof SupplierQuoteHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/profile': {
      id: '/supplier/profile'
      path: '/supplier/profile'
      fullPath: '/supplier/profile'
      preLoaderRoute: typeof SupplierProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/login': {
      id: '/supplier/login'
      path: '/supplier/login'
      fullPath: '/supplier/login'
      preLoaderRoute: typeof SupplierLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aog/$id': {
      id: '/aog/$id'
      path: '/aog/$id'
      fullPath: '/aog/$id'
      preLoaderRoute: typeof AogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/suppliers': {
      id: '/admin/suppliers'
      path: '/admin/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AdminSuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/revenue': {
      id: '/admin/revenue'
      path: '/admin/revenue'
      fullPath: '/admin/revenue'
      preLoaderRoute: typeof AdminRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/enrolments': {
      id: '/admin/enrolments'
      path: '/admin/enrolments'
      fullPath: '/admin/enrolments'
      preLoaderRoute: typeof AdminEnrolmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data': {
      id: '/admin/data'
      path: '/admin/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/comms': {
      id: '/admin/comms'
      path: '/admin/comms'
      fullPath: '/admin/comms'
      preLoaderRoute: typeof AdminCommsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/aog': {
      id: '/admin/aog'
      path: '/admin/aog'
      fullPath: '/admin/aog'
      preLoaderRoute: typeof AdminAogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/amo': {
      id: '/admin/amo'
      path: '/admin/amo'
      fullPath: '/admin/amo'
      preLoaderRoute: typeof AdminAmoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/aircraft': {
      id: '/admin/aircraft'
      path: '/admin/aircraft'
      fullPath: '/admin/aircraft'
      preLoaderRoute: typeof AdminAircraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/$': {
      id: '/api/v1/$'
      path: '/api/v1/$'
      fullPath: '/api/v1/$'
      preLoaderRoute: typeof ApiV1SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$id': {
      id: '/api/files/$id'
      path: '/api/files/$id'
      fullPath: '/api/files/$id'
      preLoaderRoute: typeof ApiFilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AircraftRoute: AircraftRoute,
  AogCasesRoute: AogCasesRoute,
  AogRiskIndexRoute: AogRiskIndexRoute,
  BillingRoute: BillingRoute,
  BrandGuidelinesRoute: BrandGuidelinesRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  EnrolRoute: EnrolRoute,
  FleetNetworkRoute: FleetNetworkRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  PartsIntelligenceRoute: PartsIntelligenceRoute,
  PrePositioningRoute: PrePositioningRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRoute,
  SetPasswordRoute: SetPasswordRoute,
  SignupRoute: SignupRoute,
  SubmitAogRoute: SubmitAogRoute,
  SubscriberAgreementRoute: SubscriberAgreementRoute,
  SupplierTermsRoute: SupplierTermsRoute,
  TeamRoute: TeamRoute,
  ValueSummaryRoute: ValueSummaryRoute,
  AdminAircraftRoute: AdminAircraftRoute,
  AdminAmoRoute: AdminAmoRoute,
  AdminAogRoute: AdminAogRoute,
  AdminCommsRoute: AdminCommsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDataRoute: AdminDataRoute,
  AdminEnrolmentsRoute: AdminEnrolmentsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminRevenueRoute: AdminRevenueRoute,
  AdminSuppliersRoute: AdminSuppliersRoute,
  AogIdRoute: AogIdRoute,
  SupplierLoginRoute: SupplierLoginRoute,
  SupplierProfileRoute: SupplierProfileRoute,
  SupplierQuoteHistoryRoute: SupplierQuoteHistoryRoute,
  SuppliersApplyRoute: SuppliersApplyRoute,
  AdminIndexRoute: AdminIndexRoute,
  SupplierIndexRoute: SupplierIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiFilesIdRoute: ApiFilesIdRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  ApiV1SplatRoute: ApiV1SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
